"""Appendix A.7 — the relaxation ladder: offline / semi-streaming / online.

The thesis body compares algorithms inside ONE model (online vertex arrival,
known i.i.d.) and asks what predictions buy there. The original project brief
suggested extending in a different direction, to streaming or offline
algorithms. This script does that at reduced scope, and arranges the result as a
ladder of relaxations of the same instance:

    offline maximum matching (Hopcroft-Karp)     unlimited memory, unlimited revision
    semi-streaming, p passes                     O(n) memory, revision across passes
    semi-streaming, 1 pass                       O(n) memory, no revision
    online vertex arrival + perfect prediction   unlimited memory, no revision
    online vertex arrival, advice-free Greedy    unlimited memory, no revision

Read downwards, the ladder separates the two things the online model forbids:
storing the graph, and changing your mind. Every entry is normalised by the same
Hopcroft-Karp optimum, on the same instances, with the same 95% CI convention as
Chapter 4, so the rows are directly comparable to the body's tables.

Outputs:
  results/streaming_ladder.json
  results/streaming_ladder_tables.md
"""
from __future__ import annotations
import json
import sys
import time
from pathlib import Path

import numpy as np

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from graphs.synthetic import (
    clvb_zipf_bipartite, left_regular_bipartite, few_types_bipartite,
)
from graphs.realworld import load_simple_graph, to_bipartite_random_partition
from iid_sampler import sample_instance
from optimal import max_matching_size
from algorithms.greedy import simple_greedy
from algorithms.ranking import ranking
from algorithms.min_predicted_degree import mpd
from algorithms.streaming import stream_multipass
from predictions.degree_truth import type_graph_degree

PASSES = 3
ROWS = ["Greedy (online)", "Ranking (online)", "MPD, perfect prediction (online)",
        "Semi-streaming, 1 pass", "Semi-streaming, 2 passes", "Semi-streaming, 3 passes"]

# Same six Network Repository graphs as Chapter 7 (Borodin et al. Table 3 set).
REAL_GRAPHS = {
    "Caltech36": "data/realworld/socfb-Caltech36/socfb-Caltech36.mtx",
    "Reed98": "data/realworld/socfb-Reed98/socfb-Reed98.mtx",
    "CE-GN": "data/realworld/bio-CE-GN/bio-CE-GN.edges",
    "CE-PG": "data/realworld/bio-CE-PG/bio-CE-PG.edges",
    "beause": "data/realworld/econ-beause/econ-beause.mtx",
    "mbeaw": "data/realworld/econ-mbeaflw/econ-mbeaflw.mtx",
}


def ci95(values) -> tuple[float, float]:
    """(mean, 95% half-width) over trials — identical convention to Chapter 4."""
    a = np.asarray(values, dtype=float)
    if a.size == 0:
        return 0.0, 0.0
    if a.size < 2:
        return float(a.mean()), 0.0
    return float(a.mean()), float(1.96 * a.std(ddof=1) / np.sqrt(a.size))


def eval_family(name, build, n_arrivals, n_trials, seed):
    """build(rng) -> (type_adj, n_right). n_arrivals=None means one arrival per
    type row, the convention Chapter 7 uses for the real graphs. Returns a panel."""
    rg, ri, rs = np.random.default_rng(seed).spawn(3)
    acc = {r: [] for r in ROWS}
    n_right = m = 0
    for _ in range(n_trials):
        type_adj, n_right = build(rg)
        m = len(type_adj) if n_arrivals is None else n_arrivals
        adj, types = sample_instance(type_adj, m=m, rng=ri)
        opt = max_matching_size(adj, n_right=n_right)
        if opt == 0:
            continue
        ts = int(rs.integers(0, 2**31 - 1))
        mu_true = type_graph_degree(type_adj, n_right=n_right)

        acc["Greedy (online)"].append(simple_greedy(adj, n_right) / opt)
        acc["Ranking (online)"].append(
            ranking(adj, n_right, np.random.default_rng(ts)) / opt)
        acc["MPD, perfect prediction (online)"].append(
            mpd(adj, n_right, mu_true, np.random.default_rng(ts)) / opt)
        sizes = stream_multipass(adj, n_right, PASSES, np.random.default_rng(ts))
        for p, s in enumerate(sizes, start=1):
            acc[f"Semi-streaming, {p} pass" + ("" if p == 1 else "es")].append(s / opt)

    n_ok = len(acc["Greedy (online)"])
    return {"graph": name, "n_right": n_right, "n_arrivals": m,
            "n_trials": n_ok,
            "rows": {r: dict(zip(("mean", "ci95"), ci95(acc[r]))) for r in ROWS}}


def render(panels) -> str:
    out = ["# Relaxation ladder: offline / semi-streaming / online",
           "",
           "Empirical competitive ratio (matching size / Hopcroft-Karp optimum),",
           f"mean +- 95% CI over trials. Machine-generated by "
           f"`scripts/run_streaming_ladder.py`.", ""]
    head = "| Algorithm (model) | " + " | ".join(p["graph"] for p in panels) + " |"
    out += [head, "|" + "---|" * (len(panels) + 1)]
    for r in ROWS:
        cells = []
        for p in panels:
            c = p["rows"][r]
            cells.append(f"{c['mean']:.3f} ± {c['ci95']:.3f}")
        out.append(f"| {r} | " + " | ".join(cells) + " |")
    out += ["", "| trials | " + " | ".join(str(p["n_trials"]) for p in panels) + " |", ""]
    return "\n".join(out)


def render_marginal(panels) -> str:
    """The like-for-like reading: what does ONE added capability buy, starting from
    the advice-free, no-revision entry of each model?

      advice   = MPD with a perfect prediction  -  Greedy            (online model)
      revision = semi-streaming 2 passes        -  semi-streaming 1  (streaming model)

    Both are measured on the same instances against the same optimum, and both
    start from a baseline that uses no prediction and never revises a decision.
    """
    defs = [("+ perfect prediction (online)",
             "MPD, perfect prediction (online)", "Greedy (online)"),
            ("+ 1 revision pass (streaming)",
             "Semi-streaming, 2 passes", "Semi-streaming, 1 pass"),
            ("+ 2 revision passes (streaming)",
             "Semi-streaming, 3 passes", "Semi-streaming, 1 pass")]
    out = ["| Graph | " + " | ".join(label for label, _, _ in defs) + " |",
           "|---|" + "---:|" * len(defs)]
    for p in panels:
        cells = [f"{p['rows'][hi]['mean'] - p['rows'][lo]['mean']:+.3f}"
                 for _, hi, lo in defs]
        out.append(f"| {p['graph']} | " + " | ".join(cells) + " |")
    return "\n".join(out) + "\n"


def main():
    t0 = time.time()
    root = Path(__file__).resolve().parent.parent
    N = 1000

    synthetic = [
        eval_family("clvb_zipf",
                    lambda rng: (clvb_zipf_bipartite(N, 1.0, rng), N), N, 40, 0),
        eval_family("left_regular d=5",
                    lambda rng: (left_regular_bipartite(N, 5, rng), N), N, 40, 1),
        eval_family("few_types r=8",
                    lambda rng: (few_types_bipartite(2000, 8, rng), 2000), 2000, 25, 2),
    ]
    print(f"[{time.time() - t0:.0f}s] synthetic panels done", flush=True)

    real = []
    for label, path in REAL_GRAPHS.items():
        n, edges = load_simple_graph(root / path)
        real.append(eval_family(
            label, lambda rng, n=n, edges=edges: to_bipartite_random_partition(n, edges, rng),
            n, 25, 7))
        print(f"[{time.time() - t0:.0f}s] {label} done", flush=True)

    res = {"passes": PASSES, "synthetic": synthetic, "realworld": real,
           "seconds": round(time.time() - t0, 1)}
    (root / "results/streaming_ladder.json").write_text(json.dumps(res, indent=2))
    md = (render(synthetic) + "\n" + render_marginal(synthetic)
          + "\n## Real-world graphs (random-partition conversion)\n\n"
          + render(real).split("\n", 5)[-1] + "\n" + render_marginal(real))
    (root / "results/streaming_ladder_tables.md").write_text(md)
    print(md)
    print(f"OK: {time.time() - t0:.0f}s")


if __name__ == "__main__":
    main()
